wl: fix __DATE__ and __TIME__ building errors
The date-time warning introduced in gcc 4.9 causes the errors:

/home/utente/kitkat-x86/kernel/drivers/net/wireless/wl/src/wl/sys/wl_linux.c: In function ‘wl_dump_ver’:
/home/utente/kitkat-x86/kernel/drivers/net/wireless/wl/src/wl/sys/wl_linux.c:2051:3: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
   __DATE__, __TIME__, EPI_VERSION_STR);
   ^
/home/utente/kitkat-x86/kernel/drivers/net/wireless/wl/src/wl/sys/wl_linux.c:2051:13: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
   __DATE__, __TIME__, EPI_VERSION_STR);
             ^

Removing the unnecessary macros __DATE__ and __TIME__ in wl_linux.c
to fix the errors.